phraseapp:
  access_token: 44a76b19f162352ae83b5207c20f4d6ef677298c0e2b459423c56cdc1d85a244
  project_id: 7ff9ad61b8936458dbea3244321f18f0
  file_format: laravel
  push:
    sources:
    - file: ./resources/lang/<locale_code>/<tag>.php
      params:
        update_translations: true
        update_descriptions: true

  pull:
    targets:
    - file: ./resources/lang/<locale_code>/attributes.php
      params:
        tag: attributes
    - file: ./resources/lang/<locale_code>/attributes_fieldset.php
      params:
        tag: attributes_fieldset
    - file: ./resources/lang/<locale_code>/auth.php
      params:
        tag: auth
    - file: ./resources/lang/<locale_code>/categories.php
      params:
        tag: categories
    - file: ./resources/lang/<locale_code>/notifications.php
      params:
        tag: notifications
    - file: ./resources/lang/<locale_code>/pagination.php
      params:
        tag: pagination
    - file: ./resources/lang/<locale_code>/passwords.php
      params:
        tag: passwords
    - file: ./resources/lang/<locale_code>/strings.php
      params:
        tag: strings
    - file: ./resources/lang/<locale_code>/validation.php
      params:
        tag: validation
    - file: ./resources/lang/<locale_code>/structures.php
      params:
        tag: structures