<?php
return [
	"accepted" => ":attribute deve essere accettato.",
	"active_url" => ":attribute non è un URL valido.",
	"after" => "attribute deve essere una data successiva a :date.",
	"after_or_equal" => ":attribute deve essere una data successiva o uguale a :date.",
	"alpha" => ":attribute può contenere solamente lettere.",
	"alpha_dash" => ":attribute può contenere solamente lettere",
	"alpha_num" => ":attribute può contenere solamente lettere e numeri.",
	"array" => ":attribute deve essere un vettore",
	"before" => ":attribute deve essere una data precedente a :date.",
	"before_or_equal" => ":attribute deve essere una data precedente o uguale a :date.",
	"between" => [
		"array" => ":attribute deve avere tra i :min e :max articoli.",
		"file" => ":attribute deve essere tra :min e :max kilobyte.",
		"numeric" => ":attribute deve essere tra :min e :max.",
		"string" => ":attribute deve avere tra i :min e :max caratteri."
	],
	"boolean" => "Il campo :attribute deve essere vero o falso",
	"confirmed" => "La conferma :attribute non corrisponde",
	"date" => ":attribute non è una data valida.",
	"date_format" => ":attribute non corrisponde al formato :format.",
	"different" => ":attribute e :other devono essere differenti.",
	"digits" => ":attribute deve essere di :digits cifre.",
	"digits_between" => ":attribute deve essere tra :min e :max cifre.",
	"dimensions" => ":attribute ha delle dimensioni d'immagine non valide.",
	"distinct" => "Il campo :attribute ha un valore duplicato.",
	"email" => "I lcampo :attributo deve essere un indirizzo email valido.",
	"exists" => ":attribute selezionato non è valido.",
	"file" => ":attribute deve essere un file.",
	"filled" => "Il campo :attributo è richiesto.",
	"image" => ":attribute deve essere un'immagine.",
	"in" => ":attribute selezonato non è valido.",
	"in_array" => "Il campo :attribute non esiste in :other.",
	"integer" => ":attribute deve essere un numero intero.",
	"ip" => ":attribute deve essere un indirizzo IP valido.",
	"json" => ":attribute deve essere una stringa JSON valida.",
	"max" => [
		"array" => ":attribute non deve avere più di :max articoli.",
		"file" => ":attribute non deve essere più grande di :max kilobyte.",
		"numeric" => ":attribute non deve essere più grande di :max.",
		"string" => ":attribute non deve essere più grande di :max caratteri."
	],
	"mimes" => ":attribute deve essere un file di tipo :values.",
	"mimetypes" => ":attribute deve essere un file di tipo :values.",
	"min" => [
		"array" => ":attribute deve avere almeno :min articoli.",
		"file" => ":attribute deve essere di almento :min kilobyte.",
		"numeric" => ":attribute deve essere almeno :min.",
		"string" => ":attribute deve essere di almento :min caratteri."
	],
	"not_in" => ":attributo selezionato non è valido.",
	"numeric" => ":attribute deve essere un numero.",
	"present" => "Il campo :attribute deve essere presente.",
	"regex" => "Il formato :attribute non è valido.",
	"required" => "Il campo :attribute è richiesto.",
	"required_if" => "Il campo :attribute è richiesto quando :other è :value.",
	"required_unless" => "Il campo :attribute è richiesto quando :other è nei :values.",
	"required_with" => "Il campo :attribute è richiesto quando :values è presente.",
	"required_with_all" => "Il campo :attribute è richiesto quando :values è presente.",
	"required_without" => "Il campo :attribute è richiesto quando :values non è presente.",
	"required_without_all" => "Il campo :attribute è richiesto quando nessuno dei :values è presente.",
	"same" => "Stesso",
	"size" => [
		"array" => ":attribute deve contenere :sixe articoli.",
		"file" => ":attribute deve essere di :size kilobyte.",
		"numeric" => ":attribute deve essere di :size.",
		"string" => ":attribute deve essere di :size caratteri."
	],
	"string" => ":attribute deve essere una stringa.",
	"timezone" => ":attribute deve essere una zona valida.",
	"unique" => ":attribute è già stato preso.",
	"uploaded" => ":attribute non è stato caricato con successo.",
	"url" => "Il formato :attribute non è valido."
];
