<?php
return [
	"accepted" => "Se debe aceptar el :attribute.",
	"active_url" => "El :attribute no es una URL válida.",
	"after" => "El :attribute debe ser una fecha posterior a :date.",
	"after_or_equal" => "El :attribute debe ser una fecha posterior o igual a :date.",
	"alpha" => "El :attribute solo debe contener letras.",
	"alpha_dash" => "El :attribute solo debe contener letras",
	"alpha_num" => "El :attribute solo debe contener letras y números.",
	"array" => "El :attribute debe ser una matriz.",
	"before" => "El :attribute debe ser una fecha anterior a :date.",
	"before_or_equal" => "El :attribute debe ser una fecha anterior o igual a :date.",
	"between" => [
		"array" => "El :attribute debe tener entre :min y :max elementos.",
		"file" => "El :attribute debe tener entre :min y :max kilobytes.",
		"numeric" => "El :attribute debe tener entre :min y :max.",
		"string" => "El :attribute debe tener entre :min y :max caracteres."
	],
	"boolean" => "El campo :attribute debe ser verdadero o falso.",
	"confirmed" => "La confirmación del :attribute no coincide.",
	"date" => "El :attribute no es una fecha válida.",
	"date_format" => "El :attribute no coincide con el formato :format.",
	"different" => "El :attribute y :other deben ser diferentes.",
	"digits" => "El :attribute debe tener :digits digitos.",
	"digits_between" => "El :attribute debe tener entre :min y :max dígitos.",
	"dimensions" => "El :attribute tiene unas dimensiones de imagen inválidas.",
	"distinct" => "El campo :attribute tiene un valor duplicado.",
	"email" => "El :attribute debe ser una dirección de correo electrónico válida.",
	"exists" => "El :attribute seleccionado es inválido.",
	"file" => "El :attribute debe ser un archivo.",
	"filled" => "El campo :attribute es obligatorio.",
	"image" => "El :attribute debe ser una imagen.",
	"in" => "El :attribute seleccionado es inválido.",
	"in_array" => "El campo :attribute no existe en :other.",
	"integer" => "El :attribute debe ser un número entero.",
	"ip" => "El :attribute debe ser una dirección de IP electrónico válida.",
	"json" => "El :attribute debe ser una cadena JSON válida.",
	"max" => [
		"array" => "El :attribute no debe tener más de :max elementos.",
		"file" => "El :attribute no debe ser mayor que :max kilobytes.",
		"numeric" => "El :attribute no debe ser mayor que :max.",
		"string" => "El :attribute no debe tener más de :max caracteres."
	],
	"mimes" => "El :attribute debe ser del tipo de archivo :values.",
	"mimetypes" => "El :attribute debe ser del tipo de archivo :values.",
	"min" => [
		"array" => "El :attribute debe tener al menos :min elementos",
		"file" => "El :attribute debe tener al menos :min kilobytes.",
		"numeric" => "El :attribute debe ser al menos :min.",
		"string" => "El :attribute debe tener al menos :min caracters."
	],
	"not_in" => "El :attribute seleccionado es inválido.",
	"numeric" => "El :attribute debe ser un número.",
	"present" => "El campo :attribute debe estar presente.",
	"regex" => "El formato de :attribute es inválido",
	"required" => "El campo :attribute es obligatorio.",
	"required_if" => "El campo :attribute es obligatorio a menos que :other sea :value.",
	"required_unless" => "El campo :attribute es obligatorio a menos que :other esté en :values.",
	"required_with" => "El campo :attribute es obligatorio cuando :values está presente.",
	"required_with_all" => "El campo :attribute es obligatorio cuando :values está presente.",
	"required_without" => "El campo :attribute es obligatorio cuando :values no está presente.",
	"required_without_all" => "El campo :attribute es obligatorio cuando ninguno de los :values está presente.",
	"same" => "Mismo",
	"size" => [
		"array" => "El :attribute debe contener :size elementos.",
		"file" => "El :attribute debe se de :size kilobytes.",
		"numeric" => "El :attribute debe ser de :size.",
		"string" => "El :attribute debe tener :size caracteres."
	],
	"string" => "El :attribute debe ser una cadena.",
	"timezone" => "El :attribute debe ser una zona válida.",
	"unique" => "El :attribute ya se ha utilizado.",
	"uploaded" => "No se ha podido actualizar el :attribute.",
	"url" => "El formato de :attribute es inválido."
];
