<?php
return [
	"accepted" => "Le :attribute doit être accepté.",
	"active_url" => "Le :attribute n'est pas une URL valide.",
	"after" => "Le :attribute doit être une date postérieure au :date.",
	"after_or_equal" => "Le :attribut doit être une date égale ou postérieure au :date.",
	"alpha" => "Le :attribute ne peut contenir que des lettres.",
	"alpha_dash" => "Le :attribute ne peut contenir que des lettres",
	"alpha_num" => "Le :attribute ne peut contenir que des lettres et des chiffres.",
	"array" => "Le :attribute must doit être une série.",
	"before" => "Le :attribute doit être une date antérieure à :date.",
	"before_or_equal" => "Le :attribute doit être une date antérieure ou égale à :date.",
	"between" => [
		"array" => "Le :attribute doit avoir entre :min et :max éléments.",
		"file" => "Le :attribute doit être compris entre :min et :max kilo-octets.",
		"numeric" => "Le :attribute doit être compris entre :min et :max.",
		"string" => "Le :attribute doit comprendre entre :min et :max caractères."
	],
	"boolean" => "Le champ :attribute doit être vrai ou faux.",
	"confirmed" => "La confirmation du :attribute ne correspond pas.",
	"date" => "Le :attribute n'est pas une date valide.",
	"date_format" => "Le :attribute ne respecte pas le format :format.",
	"different" => "Le :attribute et :other doivent être différents.",
	"digits" => "Le :attribute doit faire :digits chiffres.",
	"digits_between" => "Le :attribute doit comprendre entre :min et :max chiffres.",
	"dimensions" => "Le :attribute a des dimensions d'image non valides.",
	"distinct" => "Le champ :attribute a une valeur en double.",
	"email" => "L' :attribute doit être une adresse e-mail valide.",
	"exists" => "Le :attribute sélectionné n'est pas valide.",
	"file" => "Le :attribute doit être un fichier.",
	"filled" => "Le champ :attribute est requis.",
	"image" => "Le :attribute doit être une image.",
	"in" => "Le :attribute sélectionné n'est pas valide.",
	"in_array" => "Le champ :attribute n'existe pas dans :other.",
	"integer" => "Le :attribute doit être un nom entier.",
	"ip" => "L' :attribute doit être une adresse IP valide.",
	"json" => "Le :attribute doit être une chaîne JSON valide.",
	"max" => [
		"array" => "Le :attribute ne peut pas avoir plus de :max éléments.",
		"file" => "Le :attribute ne peut pas être supérieur à :max kilo-octets.",
		"numeric" => "Le :attribute ne peut pas être supérieur à :max.",
		"string" => "Le :attribute ne peut pas faire plus de :max caractères."
	],
	"mimes" => "Le :attribute doit être un champ de type : :values.",
	"mimetypes" => "Le :attribute doit être un fichier de type : :values.",
	"min" => [
		"array" => "Le :attribute doit avoir au moins :min éléments.",
		"file" => "Le :attribute doit faire au moins :min kilo-octets.",
		"numeric" => "Le :attribute doit faire au moins :min.",
		"string" => "Le :attribute doit faire au moins :min caractère."
	],
	"not_in" => "Le :attribute sélectionné est invalide.",
	"numeric" => "Le :attribute doit être un nombre.",
	"present" => "Le champ :attribute doit être présent.",
	"regex" => "Le format :attribute est invalide.",
	"required" => "Le champ :attribute est requis.",
	"required_if" => "Le champ :attribute est requis lorsque :other est :value.",
	"required_unless" => "Le champ :attribute est requis à moins que :other soit en :values.",
	"required_with" => "Le champ :attribute est requis lorsque :values est présent.",
	"required_with_all" => "Le champ :attribute est requis lorsque :values est présent.",
	"required_without" => "Le champ :attribute est requis lorsque :values n'est pas présent.",
	"required_without_all" => "Le champ :attribute est requis lorsqu'aucune des :values n'est présente.",
	"same" => "Identique",
	"size" => [
		"array" => "Le :attribute doit contenir :size éléments.",
		"file" => "Le :attribute doit faire :size kilo-octets.",
		"numeric" => "Le :attribute doit faire :size.",
		"string" => "Le :attribute doit faire :size caractères."
	],
	"string" => "Le :attribute doit être une chaîne.",
	"timezone" => "Le :attribute doit être une zone valide.",
	"unique" => "Le :attribute a déjà été pris.",
	"uploaded" => "Le téléchargement du :attribute a échoué.",
	"url" => "Le format du :attribute est invalide."
];
